Origin/header modal
YuriiSikorskyi/project-08_IceCream pull request #19
Opened 2022-12-22 21:33 UTC by KovalVladyslav

Сделал модалку на Header-hero
Вроде все ок, кроме одного нюанса. Какого то переноситься на вторую строчку. 
![image](https://user-images.githubusercontent.com/114920825/209230103-1c49a852-f07f-47b7-b162-0f91e625ac74.png)

2022-12-22 22:01 UTC, YuriiSikorskyi requested changes
перевір валідатором і поправ конфлікти

2022-12-22 22:29 UTC, KovalVladyslav commented
> перевір валідатором і поправ конфлікти

done, 2 mistakes due to out of DOCTYPE and HEAD tag. WIll be fixed automatically after merging. Thnx

2022-12-22 22:29 UTC, KovalVladyslav commented
> перевір валідатором і поправ конфлікти

2022-12-23 21:30 UTC, YuriiSikorskyi requested changes
Виправ конфлікт файлів, подивись відео Івана, вчора Ліза прислала, там він пояснює як це зробити

2022-12-23 21:43 UTC, KovalVladyslav commented
я смотрел, но сейчас какая то фигня. Вчера я исправил, сейчас пишет что конфликт сложный, нелья исправить, только через консоль хз как. В вскод не могу открыть, надо помощь...

2022-12-23 22:00 UTC, YuriiSikorskyi commented
> відправляти

Ок, я постараюсь щось сам придумати, тільки це буде пізніше, як буду біля ноута, бо з телефону це не реально

2022-12-23 22:14 UTC, KovalVladyslav commented
Спасибо, сори за тупняк (

2022-12-24 11:46 UTC, YuriiSikorskyi approved these changes

2022-12-24 11:50 UTC, merged